### ISSUE TITLE
Issue #1 - User can see a box which has a border-radius property applied to it.

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/border-radius-previewer#2]
## 💰 Feature

User can see a box which has a border-radius property applied to it.

## 🗒️ Notes

This will require me to build the basic structure of the page, and then create a box using CSS with the border-radius property applied to it.

## ✅ Tasks
- [x] Create a component for the border-radius-preview.
- [x] Make it render a square, with a border-radius property applied.
- [x] Add basic styling to the page.
- [x] Test, polish, kill all bugs.
