### ISSUE TITLE
Issue #2 - User can change the 4 border-radius values that are applied to the box.

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/border-radius-previewer#3]
## 💰 Feature

User can change the 4 border-radius values that are applied to the box.

## 🗒️ Notes

This will require me to create inputs for the user to enter values, as well as update the class of the PreviewBox to render a new shape.

## ✅ Tasks
- [x] Create a row under the PreviewBox with four input elements.
- [x] Create an onChange event listener and assign it to the props of all four inputs.
- [x] Enhance the onChange event listener function to update the DOM when a new input is received.
