### ISSUE TITLE
Issue #3 - User can copy the resulting CSS to the clipboard.

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/border-radius-previewer#4]
## 💰 Feature

User can copy the resulting CSS to the clipboard.

## 🗒️ Notes
This will require me to learn how to copy things to clipboard!
Then add an icon with a click event listener that will do so.

## ✅ Tasks
- [x] Learn how to copy things to clipboard.
- [x] Add an icon for the user to copy to clipboard.
- [x] Add a click event listener on the icon.
- [x] Create a handler which copies the text from the DOM into the users clipboard.
- [x] Test, polish, kill all bugs.
